version: "3.9"

services:
  app:
    build: .
    env_file:
      - .env.local
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - news-summarizer-network
    depends_on:
      - mongo
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - news-summarizer-network
    logging:
      driver: "none"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: new_secure_password
    networks:
      - news-summarizer-network
    depends_on:
      - mongo
    logging:
      driver: "none"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - news-summarizer-network
    logging:
      driver: "none"

  celery_worker:
    build: .
    command: celery -A app.CeleryConfigs.Config worker --loglevel=debug
    volumes:
      - .:/app
    networks:
      - news-summarizer-network
    depends_on:
      - redis
    logging:
      driver: "none"

  celery_beat:
    build: .
    command: celery -A app.CeleryConfigs.Config beat --loglevel=debug
    volumes:
      - .:/app
    networks:
      - news-summarizer-network
    depends_on:
      - redis
    logging:
      driver: "none"

networks:
  news-summarizer-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: